services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ""
    image: n8nio/n8n
    autoDeploy: false
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
